In [5]:
import numpy as np
# 2 x 3 行列
A = np.array([[1,2,3],[4,5,6]])
print(A)
print(A.shape) # インスタンス変数 shape: ndarrayの要素の数

[[1 2 3]
 [4 5 6]]
(2, 3)


In [9]:
# 3 x 2行列
B = np.array([[1,2],[3,4],[5,6]])
print(B)
print(B.shape)

[[1 2]
 [3 4]
 [5 6]]
(3, 2)


In [10]:
A = np.array([[1,2,3],[4,5,6]])
print(A.ndim) # インスタンス変数 ndim: 次元の数

2


In [11]:
A = np.array([[1,2,3],[4,5,6]]) # 整数
print(A.dtype)

int32


In [13]:
B = np.array([[1,2,3],[4,5,6]], np.float64)
print(B.dtype) # インスタンス変数 dtype: 要素のデータ型

float64


In [17]:
A = np.array([0,1,2,3,4,5,6,7,8]) # スライシングによる選択
print(A[1:7:2]) # 要素1～6までステップ数2で出力

[1 3 5]


In [28]:
# i,j,kはそれぞれ省略可能
print(A[5:]) # 要素5から全て
print(A[:5]) # 要素4まで全て
print(A[3:7]) # 要素3から6まで
print(A[0:8]) # 要素8まで

[5 6 7 8]
[0 1 2 3 4]
[3 4 5 6]
[0 1 2 3 4 5 6 7]


In [30]:
# ndarrayのインデックスには負の値を指定することも可能
print(A[-2]) #最後から2番目の要素

7


In [35]:
# 負のインデックス指定を併用したスライシングの例
print(A[-1:2:-2]) 

[8 6 4]
